name: ucsc_bedtobigbed
description: Convert file from bed to bigBed format
keywords:
  - bed
  - bigbed
  - ucsc
  - bedtobigbed
  - converter
tools:
  - ucsc:
      description: Convert file from bed to bigBed format
      homepage: http://hgdownload.cse.ucsc.edu/admin/exe/
      documentation: https://genome.ucsc.edu/goldenPath/help/bigBed.html
      licence: ["varies; see http://genome.ucsc.edu/license"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: bed file
        pattern: "*.{bed}"
        ontologies: []
  - sizes:
      type: file
      description: chromosome sizes file
      pattern: "*.{sizes}"
      ontologies: []
  - autosql:
      type: file
      description: autoSql file to describe the columns of the BED file
      pattern: "*.{as}"
      ontologies: []
output:
  bigbed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bigBed":
          type: file
          description: bigBed file
          pattern: "*.{bigBed}"
          ontologies: []
  versions_ucsc:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ucsc:
          type: string
          description: The name of the tool
      - "482":
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ucsc:
          type: string
          description: The name of the tool
      - "482":
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@drpatelh"
maintainers:
  - "@drpatelh"
