name: ucsc_gtftogenepred
description: compute average score of bigwig over bed file
keywords:
  - gtf
  - genepred
  - refflat
  - ucsc
  - gtftogenepred
tools:
  - ucsc:
      description: Convert GTF files to GenePred format
      homepage: http://hgdownload.cse.ucsc.edu/admin/exe/
      licence: ["varies; see http://genome.ucsc.edu/license"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - gtf:
        type: file
        description: GTF file
        pattern: "*.{gtf}"
        ontologies: []
output:
  genepred:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.genepred":
          type: file
          description: genepred file
          pattern: "*.{genepred}"
          ontologies: []
  refflat:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.refflat":
          type: file
          description: refflat file
          pattern: "*.{refflat}"
          ontologies: []
  versions_ucsc:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ucsc:
          type: string
          description: The name of the tool
      - "482":
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ucsc:
          type: string
          description: The name of the tool
      - "482":
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@BarryDigby"
  - "@anoronh4"
maintainers:
  - "@BarryDigby"
  - "@anoronh4"
