name: "fastqdl"
description: Download FASTQ files from SRA or ENA repositories.
keywords:
  - download
  - ena
  - fastq
  - sra
tools:
  - "fastqdl":
      description: "A tool to download FASTQs associated with Study, Experiment, or
        Run accessions."
      homepage: "https://github.com/rpetit3/fastq-dl"
      documentation: "https://github.com/rpetit3/fastq-dl"
      tool_dev_url: "https://github.com/rpetit3/fastq-dl"
      doi: "10.5281/zenodo.13957735"
      licence:
        - "MIT"
      identifier: biotools:fastq-dl
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - accession:
        type: string
        description: ENA/SRA accession to query
output:
  fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.fastq.gz":
          type: file
          description: FASTQ files downloaded from ENA or SRA
          pattern: "*.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  runinfo:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*-run-info.tsv":
          type: file
          description: Tab-delimited file containing metadata for each Run
            downloaded
          pattern: "*-run-info.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475
  runmergers:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*-run-mergers.tsv":
          type: file
          description: Tab-delimited file merge information from
            --group-by-experiment or --group-by-sample
          pattern: "*-run-mergers.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475
  versions_fastqdl:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastq-dl:
          type: string
          description: The name of the tool
      - fastq-dl --version |& sed "s/.* //":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fastq-dl:
          type: string
          description: The name of the tool
      - fastq-dl --version |& sed "s/.* //":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@camlloyd"
maintainers:
  - "@camlloyd"
