name: "svtools_vcftobedpe"
description: Convert a VCF file to a BEDPE file.
keywords:
  - structural
  - bedpe
  - vcf
  - conversion
  - variants
tools:
  - "svtools":
      description: "Tools for processing and analyzing structural variants"
      tool_dev_url: "https://github.com/hall-lab/svtools"
      licence:
        - "MIT License"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - vcf:
        type: file
        description: Input VCF file containing structural variants
        pattern: "*.{vcf,vcf.gz}"
        ontologies: []
output:
  bedpe:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.bedpe":
          type: file
          description: The converted BEDPE file
          pattern: "*.bedpe"
          ontologies: []
  versions_svtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - svtools:
          type: string
          description: The name of the tool
      - svtools --version |& sed 's/svtools //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - svtools:
          type: string
          description: The name of the tool
      - svtools --version |& sed 's/svtools //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
