name: "bioformats2raw"
description: Java application to convert image file formats, including .mrxs, to
  an intermediate Zarr structure compatible with the OME-NGFF specification.
keywords:
  - zarr
  - ome-ngff
  - imaging
tools:
  - "bioformats2raw":
      description: "Java application to convert image file formats, including .mrxs,
        to an intermediate Zarr structure compatible with the OME-NGFF specification."
      homepage: "https://github.com/glencoesoftware/bioformats2raw"
      documentation: "https://github.com/glencoesoftware/bioformats2raw"
      tool_dev_url: "https://github.com/glencoesoftware/bioformats2raw"
      licence:
        - "GPL-2.0"
      identifier: biotools:bioformats2raw
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`
    - image:
        type: file
        description: bioformats supported image file format
        pattern: "*.{tif,tiff,svs,mrxs}"
        ontologies:
          - edam: "http://edamontology.org/format_3727"
          - edam: "http://edamontology.org/format_3591"
output:
  omezarr:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1']`
      - "*ome.zarr":
          type: directory
          description: OME-Zarr fileset for image data storage. Specification can
            be found at https://ngff.openmicroscopy.org/latest/#storage-format
          pattern: "*{ome.zarr}"
          ontologies:
            - edam: "http://edamontology.org/format_3915"
  versions_bioformats2raw:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bioformats2raw:
          type: string
          description: The name of the tool
      - bioformats2raw --version |& sed -n "1s/Version = //p":
          type: eval
          description: The expression to obtain the version of the tool
  versions_bioformats:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bio-formats:
          type: string
          description: The name of the tool
      - bioformats2raw --version |& sed -n "2s/Bio-Formats version = //p":
          type: eval
          description: The expression to obtain the version of the tool
  versions_ngff:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngff:
          type: string
          description: The name of the tool
      - bioformats2raw --version |& sed -n "3s/NGFF specification version = //p":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bioformats2raw:
          type: string
          description: The name of the tool
      - bioformats2raw --version |& sed -n "1s/Version = //p":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - bio-formats:
          type: string
          description: The name of the tool
      - bioformats2raw --version |& sed -n "2s/Bio-Formats version = //p":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngff:
          type: string
          description: The name of the tool
      - bioformats2raw --version |& sed -n "3s/NGFF specification version = //p":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@CaroAMN"
maintainers:
  - "@CaroAMN"
