name: "smoove_call"
description: smoove simplifies and speeds calling and genotyping SVs for short
  reads. It also improves specificity by removing many spurious alignment
  signals that are indicative of low-level noise and often contribute to
  spurious calls. Developed by Brent Pedersen.
keywords:
  - structural variants
  - SV
  - vcf
  - wgs
tools:
  - "smoove":
      description: "structural variant calling and genotyping with existing tools, but,
        smoothly"
      homepage: https://github.com/brentp/smoove
      documentation: https://brentp.github.io/post/smoove/
      tool_dev_url: https://github.com/brentp/smoove
      licence:
        - "Apache-2.0"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM file
        pattern: "*.{bam,cram}"
        ontologies: []
    - index:
        type: file
        description: Index of BAM/CRAM file
        pattern: "*.{bai,crai}"
        ontologies: []
    - exclude_beds:
        type: file
        description: A BED file containing the regions to exclude from the SV
          calling
        pattern: "*.bed"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.{fasta,fna,fa}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: Index of reference fasta file
        pattern: "*.fai"
        ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: Compressed VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  versions_smoove:
    - - ${task.process}:
          type: string
          description: The name of the process
      - smoove:
          type: string
          description: The name of the tool
      - "smoove -v |& sed -n 's/smoove version: *//p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - smoove:
          type: string
          description: The name of the tool
      - "smoove -v |& sed -n 's/smoove version: *//p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@scorreard"
  - "@nvnieuwk"
maintainers:
  - "@scorreard"
  - "@nvnieuwk"
