name: "custom_sratoolsncbisettings"
description: Test for the presence of suitable NCBI settings or create them on
  the fly.
keywords:
  - NCBI
  - settings
  - sra-tools
  - prefetch
  - fasterq-dump
tools:
  - "sratools":
      description: "SRA Toolkit and SDK from NCBI"
      homepage: https://github.com/ncbi/sra-tools
      documentation: https://github.com/ncbi/sra-tools/wiki
      tool_dev_url: https://github.com/ncbi/sra-tools
      licence:
        - "Public Domain"
      identifier: ""
input:
  - ids:
      type: string
      description: List of id settings
output:
  ncbi_settings:
    - "*.mkfg":
        type: file
        description: An NCBI user settings file.
        pattern: "*.mkfg"
        ontologies: []
  versions_sratools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - sratools:
          type: string
          description: The name of the tool
      - prefetch --version 2>&1 | grep -Eo '[0-9.]+':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - sratools:
          type: string
          description: The name of the tool
      - prefetch --version 2>&1 | grep -Eo '[0-9.]+':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@Midnighter"
maintainers:
  - "@Midnighter"
