name: "crabz_compress"
description: Compress files with crabz
keywords:
  - compression
  - gzip
  - zlib
tools:
  - crabz:
      description: "Like pigz, but rust"
      homepage: "https://github.com/sstadick/crabz"
      documentation: "https://github.com/sstadick/crabz"
      tool_dev_url: "https://github.com/sstadick/crabz"
      licence:
        - "MIT"
      identifier: biotools:crabz
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - file:
        type: file
        description: File to be compressed
        pattern: "*.*"
        ontologies: []
output:
  archive:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.gz":
          type: file
          description: The compressed file
          pattern: "*.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  versions_crabz:
    - - ${task.process}:
          type: string
          description: The name of the process
      - crabz:
          type: string
          description: The name of the tool
      - 0.10.0:
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - crabz:
          type: string
          description: The name of the tool
      - 0.10.0:
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@camlloyd"
maintainers:
  - "@camlloyd"
