name: "pygenprop_info"
description: |
  Display a summary of the contents of a Micromeda file, including the number of samples,
  genome property assignments, step assignments, InterProScan matches, and protein sequences.
keywords:
  - genome properties
  - functional annotation
  - interproscan
  - pathway analysis
  - micromeda
  - summary
tools:
  - "pygenprop":
      description: A python library for programmatic usage of EBI InterPro Genome Properties.
      homepage: "https://github.com/Micromeda/pygenprop"
      documentation: "https://pygenprop.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/Micromeda/pygenprop"
      licence:
        - "Apache-2.0"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - meda:
        type: file
        description: |
          Micromeda SQLite database containing Genome Properties assignments
          (output of pygenprop build)
        pattern: "*.micro"
        ontologies:
          - edam: "http://edamontology.org/format_3621" # SQLite format
output:
  info:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.info":
          type: file
          description: |
            Plain-text summary report of the Micromeda file contents, including counts of
            samples, genome property assignments, step assignments, InterProScan matches,
            and protein sequences
          pattern: "*.info"
          ontologies:
            - edam: "http://edamontology.org/format_2330" # Textual format
  versions_pygenprop:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pygenprop:
          type: string
          description: The name of the tool
      - '"1.1"':
          type: string
          description: The expression to obtain the version of the tool
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python -V | sed "s/Python //g":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pygenprop:
          type: string
          description: The name of the tool
      - '"1.1"':
          type: string
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python -V | sed "s/Python //g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@vagkaratzas"
maintainers:
  - "@vagkaratzas"
