name: samshee
description: Module to validate illumina® Sample Sheet v2 files.
keywords:
  - samplesheet
  - illumina
  - bclconvert
  - bcl2fastq
tools:
  - samshee:
      description: A schema-agnostic parser and writer for illumina® sample sheets
        v2 and similar documents.
      homepage: https://github.com/lit-regensburg/samshee
      documentation: https://github.com/lit-regensburg/samshee/blob/main/README.md
      tool_dev_url: https://github.com/lit-regensburg/samshee
      licence:
        - MIT license
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', lane:1 ]
    - samplesheet:
        type: file
        description: "illumina v2 samplesheet"
        pattern: "*.{csv}"
        ontologies:
          - edam: http://edamontology.org/format_3752
  - file_schema_validator:
      type: string
      description: "Optional JSON file used additional samplesheet validation settings"
output:
  samplesheet:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', lane:1 ]
      - "*_formatted.csv":
          type: file
          description: "illumina v2 samplesheet"
          ontologies: []
  versions_samshee:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samshee:
          type: string
          description: The name of the tool
      - 0.2.13:
          type: string
          description: The expression to obtain the version of the tool
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version | sed -e "s/Python //g":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samshee:
          type: string
          description: The name of the tool
      - 0.2.13:
          type: string
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version | sed -e "s/Python //g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nschcolnicov"
maintainers:
  - "@nschcolnicov"
