name: narfmap_align
description: Performs fastq alignment to a reference using NARFMAP
keywords:
  - alignment
  - map
  - fastq
  - bam
  - sam
tools:
  - narfmap:
      description: narfmap is a fork of the Dragen mapper/aligner Open Source
        Software.
      homepage: https://github.com/bioinformaticsorphanage/NARFMAP
      documentation: https://github.com/bioinformaticsorphanage/NARFMAP/blob/main/doc/usage.md#basic-command-line-usage
      tool_dev_url: https://github.com/bioinformaticsorphanage/NARFMAP
      licence:
        - "GPL v3"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - hashmap:
        type: file
        description: NARFMAP hash table
        pattern: "Directory containing NARFMAP hash table *.{cmp,.bin,.txt}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: Reference genome in FASTA format
        pattern: "*.{fasta,fa,fna}"
        ontologies: []
  - sort_bam:
      type: boolean
      description: Sort the BAM file after alignment
output:
  bam:
    - - meta:
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
          ontologies: []
      - "*.bam":
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
          ontologies: []
  log:
    - - meta:
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
          ontologies: []
      - "*.log":
          type: file
          description: Log file of NARFMAP run
          pattern: "*{.log}"
          ontologies: []
  versions_narfmap:
    - - ${task.process}:
          type: string
          description: The name of the process
      - narfmap:
          type: string
          description: The name of the tool
      - dragen-os --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
  versions_pigz:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed 's/pigz //g':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - narfmap:
          type: string
          description: The name of the tool
      - dragen-os --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed 's/pigz //g':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@edmundmiller"
maintainers:
  - "@edmundmiller"
