name: "fqtk"
description: Demultiplex fastq files
keywords:
  - demultiplex
  - fastq
  - rust
tools:
  - "fqtk":
      description: "A toolkit for working with FASTQ files, written in Rust."
      homepage: "https://github.com/fulcrumgenomics/fqtk"
      documentation: "https://github.com/fulcrumgenomics/fqtk"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - sample_sheet:
        type: file
        description: Tsv file, with two columns sample_id and barcode
        pattern: "*.{tsv}"
        ontologies:
          - edam: http://edamontology.org/format_3475
    - fastq_folder:
        type: file
        description: Directory containing fastq files that will be staged as
          'input' folder
        pattern: "*"
        ontologies: []
    - fastq_readstructure_pairs:
        type: map
        description: List of lists i.e. [[<fastq file name>, <read
          structure>],...]
output:
  sample_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - output/*.fq.gz:
          type: file
          description: Demultiplexed per-sample FASTQ files
          pattern: "output/*R*.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  metrics:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - output/demux-metrics.txt:
          type: file
          description: |
            Demultiplexing summary stats; sample_id, barcode templates, frac_templates, ratio_to_mean, ratio_to_best
          pattern: "output/demux-metrics.txt"
          ontologies: []
  most_frequent_unmatched:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - output/unmatched*.fq.gz:
          type: file
          description: |
            File containing unmatched fastq records
          pattern: "output/unmatched*.fq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  versions_fqtk:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fqtk:
          type: string
          description: The name of the tool
      - fqtk --version 2>&1 | cut -d " " -f2:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - fqtk:
          type: string
          description: The name of the tool
      - fqtk --version 2>&1 | cut -d " " -f2:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nh13"
  - "@sam-white04"
maintainers:
  - "@nh13"
  - "@sam-white04"
