name: "pharmcat_phenotyper"
description: |
  The PharmCAT Phenotyper is a core module of the Pharmacogenomics Clinical Annotation Tool
  that translates patient diplotypes into specific, actionable metabolizer phenotypes
  (e.g., Poor Metabolizer). It operates by analyzing the JSON output from the Named
  Allele Matcher, mapping these results to established clinical guidelines (such as
  CPIC) to predict drug response.
keywords:
  - vcf
  - pharmcat
  - phenotyper
  - PGx
tools:
  - "pharmcat":
      description: |
        "PharmCAT (Pharmacogenomics Clinical Annotation Tool) is a bioinformatics
        tool that analyzes genetic variants to predict drug response and tailor medical
        treatment to an individual patient’s genetic profile."
      homepage: "https://pharmcat.clinpgx.org/"
      documentation: "https://pharmcat.clinpgx.org/"
      tool_dev_url: "https://github.com/PharmGKB/PharmCAT"
      doi: "10.1002/cpt.928"
      licence:
        - "MPL-2.0"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', name:'test_sample' ]`
    - match_json:
        type: file
        description: The Json output from the matcher module of pharmcat
        pattern: "*.json"
        ontologies:
          - edam: http://edamontology.org/format_3464
    - outside_match_tsv:
        type: file
        description: Tab seperated file containing diplotypes calls from other
          callers
        pattern: "*.tsv"
        ontologies:
          - edam: http://edamontology.org/format_3475
output:
  phenotyper_json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', name:'test_sample' ]`
      - "*.phenotype.json":
          type: file
          description: Json output from the phenotyper module of PharmCAT
          pattern: "*.phenotype.json"
          ontologies:
            - edam: http://edamontology.org/format_3464
  versions_pharmcat:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pharmcat:
          type: string
          description: The name of the tool
      - pharmcat --version | cut -f2 -d ' ':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pharmcat:
          type: string
          description: The name of the tool
      - pharmcat --version | cut -f2 -d ' ':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@ramsainanduri"
maintainers:
  - "@ramsainanduri"
