# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_dedup_stats_samtools_umitools"
description: UMI-tools dedup, index BAM file and run samtools stats, flagstat and idxstats
keywords:
  - umi
  - dedup
  - index
  - bam
  - sam
  - cram
components:
  - umitools/dedup
  - samtools/index
  - samtools/view
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat
  - bam_stats_samtools
input:
  - ch_bam_bai:
      description: |
        input BAM file
        Structure: [ val(meta), path(bam), path(bai) ]
  - val_get_dedup_stats:
      type: boolean
      description: |
        Generate output stats when running "umi_tools dedup"
  - val_primary_only:
      type: boolean
      description: |
        Filter to primary alignments (SAM flag 0x900) before running UMI-tools dedup.
        When true, secondary and supplementary alignments are removed so that dedup
        statistics reflect only primary alignments.
output:
  - bam:
      description: |
        Umi deduplicated BAM/SAM file
        Structure: [ val(meta), path(bam) ]
  - bai:
      description: |
        Umi deduplicated BAM/SAM samtools index
        Structure: [ val(meta), path(bai) ]
  - csi:
      description: |
        CSI samtools index
        Structure: [ val(meta), path(csi) ]
  - deduplog:
      description: |
        UMI-tools deduplication log
        Structure: [ val(meta), path(log) ]
  - stats:
      description: |
        File containing samtools stats output
        Structure: [ val(meta), path(stats) ]
  - flagstat:
      description: |
        File containing samtools flagstat output
        Structure: [ val(meta), path(flagstat) ]
  - idxstats:
      description: |
        File containing samtools idxstats output
        Structure: [ val(meta), path(idxstats) ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@drpatelh"
  - "@KamilMaliszArdigen"
maintainers:
  - "@drpatelh"
  - "@KamilMaliszArdigen"
