name: "wisecondorx_gender"
description: Returns the gender of a .npz resulting from convert, based on a
  Gaussian mixture model trained during the newref phase
keywords:
  - copy number analysis
  - gender determination
  - npz
tools:
  - "wisecondorx":
      description: "WIthin-SamplE COpy Number aberration DetectOR, including sex chromosomes"
      homepage: "https://github.com/CenterForMedicalGeneticsGhent/WisecondorX"
      documentation: "https://github.com/CenterForMedicalGeneticsGhent/WisecondorX"
      tool_dev_url: "https://github.com/CenterForMedicalGeneticsGhent/WisecondorX"
      doi: "10.1093/nar/gky1263"
      licence:
        - "Attribution-NonCommercial-ShareAlike CC BY-NC-SA"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - npz:
        type: file
        description: Single sample NPZ file (from which to determine the gender)
        pattern: "*.npz"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reference:
        type: file
        description: Reference NPZ file
        pattern: "*.npz"
        ontologies: []
output:
  gender:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  versions_wisecondorx:
    - - ${task.process}:
          type: string
          description: The name of the process
      - wisecondorx:
          type: string
          description: The name of the tool
      - pip list |& sed -n 's/wisecondorx *//p':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - wisecondorx:
          type: string
          description: The name of the tool
      - pip list |& sed -n 's/wisecondorx *//p':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
